package pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2 dic. 2022 13:48:54 by Hibernate Tools 5.6.7.Final
@Entity
@Table(name="zoologicos")
/**
 * Zoologicos generated by hbm2java
 */
public class Zoologico implements java.io.Serializable {
	@Id
	@Column(name ="id")
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private int id;
	@Column(name="nombre",unique=true, nullable=false ,length=40)
	private String nombre;
	@Column(name="ciudad",unique=true, nullable=false ,length=40)
	private String ciudad;
	@Column(name="anyo_fundacion",nullable=false,length=10)
	private int anyoFundacion;

	public Zoologico() {
	}

	public Zoologico(int id, String nombre, String ciudad, int anyoFundacion) {
		this.id = id;
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anyoFundacion = anyoFundacion;
	}

	public Zoologico(String nombre, String ciudad, int anyoFundacion) {
		this.nombre = nombre;
		this.ciudad = ciudad;
		this.anyoFundacion = anyoFundacion;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getAnyoFundacion() {
		return this.anyoFundacion;
	}

	public void setAnyoFundacion(int anyoFundacion) {
		this.anyoFundacion = anyoFundacion;
	}

}
